apiVersion: "cilium.io/v2alpha1"
kind: CiliumL2AnnouncementPolicy
metadata:
 name: announcement-policy-1
 namespace: "kube-system"
spec:
 externalIPs: false
 loadBalancerIPs: true
 interfaces:
  - ^eth[0-9]+ 
